<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="ST_NestStatistics" Id="{980539a7-3419-44a4-b772-051e36a050d9}" SpecialFunc="None">
    <Declaration><![CDATA[TYPE ST_NestStatistics :
STRUCT
    udiTotalTests : UDINT;
    udiGoodParts  : UDINT;
    udiBadParts   : UDINT;
END_STRUCT
END_TYPE]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>